version: '3'
services:

  web:
    stdin_open: true
    tty: true
    build: .
    entrypoint: ./server-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PGHOST: ${PGHOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - webnet

  db:
    image: postgres:13
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - webnet
    
networks:
  webnet:

volumes:
  pgdata:
